version: 2

updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: '[Actions]'
    labels:
      - dependabot
      - github-actions-deps
